### ISSUE TITLE
aarch64 not picked up by get_arch()

### ISSUE THREAD

**Issue by plagerweij** [virtualstaticvoid/asdf-kind#1]
On Fedora Silverblue aarch64, running `asdf install kind <version>` doesn't download the arm64 version of kind.

Adding aarch64 to the case statement fixes the issue:

```diff
--- a/bin/install
+++ b/bin/install
@@ -35,7 +35,7 @@ get_arch() {
    amd64 | x86_64)
      echo "amd64"
      ;;
-   arm64)
+   arm64 | aarch64)
      echo "arm64"
      ;;
    ppc64le)
```

**Comment by virtualstaticvoid** [comment]
Support for `aarch64` implemented.
